// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
non_camel_case_types,
unused,
non_snake_case,
clippy::needless_return,
clippy::redundant_closure_call,
clippy::redundant_closure,
clippy::useless_conversion,
clippy::unit_arg,
clippy::unused_unit,
clippy::double_parens,
clippy::let_and_return,
clippy::too_many_arguments,
clippy::match_single_binding,
clippy::clone_on_copy,
clippy::let_unit_value,
clippy::deref_addrof,
clippy::explicit_auto_deref,
clippy::borrow_deref_ref,
clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
                    default_stream_sink_codec = SseCodec,
                    default_rust_opaque = RustOpaqueMoi,
                    default_rust_auto_opaque = RustAutoOpaqueMoi,
                );
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1184596833;
            

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__parser__init_app_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "init_app", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok({ crate::api::parser::init_app(); })?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__parser__parse_mcap_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "parse_mcap", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
let api_buf = <Vec<u8>>::sse_decode(&mut deserializer);
let api_types = <Vec<crate::api::parser::RecordType>>::sse_decode(&mut deserializer);
let api_sink = <StreamSink<crate::api::parser::McapRecord,flutter_rust_bridge::for_generated::SseCodec>>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok({ crate::api::parser::parse_mcap(api_path, api_buf, api_types, api_sink); })?;   Ok(output_ok)
                    })())
                } })
            }

// Section: dart2rust


                impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);}
                }
                
                impl SseDecode for chrono::DateTime::<chrono::Utc> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i64>::sse_decode(deserializer);
        return chrono::DateTime::<chrono::Utc>::from_naive_utc_and_offset(chrono::DateTime::from_timestamp_micros(inner).expect("invalid or out-of-range datetime").naive_utc(), chrono::Utc);}
                }
                
                impl SseDecode for std::collections::HashMap<String, String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <Vec<(String,String,)>>::sse_decode(deserializer);
        return inner.into_iter().collect();}
                }
                
                impl SseDecode for StreamSink<crate::api::parser::McapRecord,flutter_rust_bridge::for_generated::SseCodec> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);}
                }
                
                impl SseDecode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();}
                }
                
                impl SseDecode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_i32::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for i64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_i64::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<u8>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Vec<(String,String,)> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<(String,String,)>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Vec<crate::api::parser::RecordType> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<crate::api::parser::RecordType>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for crate::api::parser::McapAttachmentInfo {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_logTime = <chrono::DateTime::<chrono::Utc>>::sse_decode(deserializer);
let mut var_createTime = <chrono::DateTime::<chrono::Utc>>::sse_decode(deserializer);
let mut var_name = <String>::sse_decode(deserializer);
let mut var_mediaType = <String>::sse_decode(deserializer);
let mut var_crc = <u32>::sse_decode(deserializer);
let mut var_data = <Vec<u8>>::sse_decode(deserializer);
return crate::api::parser::McapAttachmentInfo{log_time: var_logTime, create_time: var_createTime, name: var_name, media_type: var_mediaType, crc: var_crc, data: var_data};}
                }
                
                impl SseDecode for crate::api::parser::McapChannelInfo {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_id = <u16>::sse_decode(deserializer);
let mut var_topic = <String>::sse_decode(deserializer);
let mut var_messageEncoding = <String>::sse_decode(deserializer);
let mut var_schemaId = <u16>::sse_decode(deserializer);
let mut var_metadata = <std::collections::HashMap<String, String>>::sse_decode(deserializer);
return crate::api::parser::McapChannelInfo{id: var_id, topic: var_topic, message_encoding: var_messageEncoding, schema_id: var_schemaId, metadata: var_metadata};}
                }
                
                impl SseDecode for crate::api::parser::McapMessage {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_channelId = <u16>::sse_decode(deserializer);
let mut var_logTime = <chrono::DateTime::<chrono::Utc>>::sse_decode(deserializer);
let mut var_publishTime = <chrono::DateTime::<chrono::Utc>>::sse_decode(deserializer);
let mut var_data = <Vec<u8>>::sse_decode(deserializer);
return crate::api::parser::McapMessage{channel_id: var_channelId, log_time: var_logTime, publish_time: var_publishTime, data: var_data};}
                }
                
                impl SseDecode for crate::api::parser::McapMetadataInfo {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_name = <String>::sse_decode(deserializer);
let mut var_metadata = <std::collections::HashMap<String, String>>::sse_decode(deserializer);
return crate::api::parser::McapMetadataInfo{name: var_name, metadata: var_metadata};}
                }
                
                impl SseDecode for crate::api::parser::McapRecord {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut tag_ = <i32>::sse_decode(deserializer);
            match tag_ {0 => { let mut var_field0 = <crate::api::parser::McapSchemaInfo>::sse_decode(deserializer);
return crate::api::parser::McapRecord::Schema(var_field0); }
1 => { let mut var_field0 = <crate::api::parser::McapChannelInfo>::sse_decode(deserializer);
return crate::api::parser::McapRecord::Channel(var_field0); }
2 => { let mut var_field0 = <crate::api::parser::McapMessage>::sse_decode(deserializer);
return crate::api::parser::McapRecord::Message(var_field0); }
3 => { let mut var_field0 = <crate::api::parser::McapMetadataInfo>::sse_decode(deserializer);
return crate::api::parser::McapRecord::Metadata(var_field0); }
4 => { let mut var_field0 = <crate::api::parser::McapAttachmentInfo>::sse_decode(deserializer);
return crate::api::parser::McapRecord::Attachment(var_field0); }
5 => { let mut var_field0 = <String>::sse_decode(deserializer);
return crate::api::parser::McapRecord::Error(var_field0); }
6 => { return crate::api::parser::McapRecord::End; }
 _ => { unimplemented!(""); }}}
                }
                
                impl SseDecode for crate::api::parser::McapSchemaInfo {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_id = <u16>::sse_decode(deserializer);
let mut var_name = <String>::sse_decode(deserializer);
let mut var_encoding = <String>::sse_decode(deserializer);
let mut var_data = <Vec<u8>>::sse_decode(deserializer);
return crate::api::parser::McapSchemaInfo{id: var_id, name: var_name, encoding: var_encoding, data: var_data};}
                }
                
                impl SseDecode for (String,String,) {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_field0 = <String>::sse_decode(deserializer);
let mut var_field1 = <String>::sse_decode(deserializer);
return (var_field0, var_field1);}
                }
                
                impl SseDecode for crate::api::parser::RecordType {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::parser::RecordType::Metadata,
1 => crate::api::parser::RecordType::Channel,
2 => crate::api::parser::RecordType::Schema,
3 => crate::api::parser::RecordType::Attachment,
4 => crate::api::parser::RecordType::Message,
5 => crate::api::parser::RecordType::End,
            _ => unreachable!("Invalid variant for RecordType: {}", inner),
        };}
                }
                
                impl SseDecode for u16 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u16::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u32::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap()}
                }
                
                impl SseDecode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
                }
                
                impl SseDecode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap() != 0}
                }
                
                fn pde_ffi_dispatcher_primary_impl(
                    func_id: i32,port: flutter_rust_bridge::for_generated::MessagePort,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                )  {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        1 => wire__crate__api__parser__init_app_impl(port, ptr, rust_vec_len, data_len),
2 => wire__crate__api__parser__parse_mcap_impl(port, ptr, rust_vec_len, data_len),
                        _ => unreachable!(),
                    }
                }
                
                fn pde_ffi_dispatcher_sync_impl(
                    func_id: i32,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        
                        _ => unreachable!(),
                    }
                }
                

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::parser::McapAttachmentInfo {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.log_time.into_into_dart().into_dart(),
self.create_time.into_into_dart().into_dart(),
self.name.into_into_dart().into_dart(),
self.media_type.into_into_dart().into_dart(),
self.crc.into_into_dart().into_dart(),
self.data.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::parser::McapAttachmentInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::parser::McapAttachmentInfo> for crate::api::parser::McapAttachmentInfo {
            fn into_into_dart(self) -> crate::api::parser::McapAttachmentInfo {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::parser::McapChannelInfo {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.id.into_into_dart().into_dart(),
self.topic.into_into_dart().into_dart(),
self.message_encoding.into_into_dart().into_dart(),
self.schema_id.into_into_dart().into_dart(),
self.metadata.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::parser::McapChannelInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::parser::McapChannelInfo> for crate::api::parser::McapChannelInfo {
            fn into_into_dart(self) -> crate::api::parser::McapChannelInfo {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::parser::McapMessage {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.channel_id.into_into_dart().into_dart(),
self.log_time.into_into_dart().into_dart(),
self.publish_time.into_into_dart().into_dart(),
self.data.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::parser::McapMessage {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::parser::McapMessage> for crate::api::parser::McapMessage {
            fn into_into_dart(self) -> crate::api::parser::McapMessage {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::parser::McapMetadataInfo {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.name.into_into_dart().into_dart(),
self.metadata.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::parser::McapMetadataInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::parser::McapMetadataInfo> for crate::api::parser::McapMetadataInfo {
            fn into_into_dart(self) -> crate::api::parser::McapMetadataInfo {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::parser::McapRecord {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {crate::api::parser::McapRecord::Schema(field0) => { [0.into_dart(),
field0.into_into_dart().into_dart()].into_dart() }
crate::api::parser::McapRecord::Channel(field0) => { [1.into_dart(),
field0.into_into_dart().into_dart()].into_dart() }
crate::api::parser::McapRecord::Message(field0) => { [2.into_dart(),
field0.into_into_dart().into_dart()].into_dart() }
crate::api::parser::McapRecord::Metadata(field0) => { [3.into_dart(),
field0.into_into_dart().into_dart()].into_dart() }
crate::api::parser::McapRecord::Attachment(field0) => { [4.into_dart(),
field0.into_into_dart().into_dart()].into_dart() }
crate::api::parser::McapRecord::Error(field0) => { [5.into_dart(),
field0.into_into_dart().into_dart()].into_dart() }
crate::api::parser::McapRecord::End => { [6.into_dart()].into_dart() }
 _ => { unimplemented!(""); }}
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::parser::McapRecord {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::parser::McapRecord> for crate::api::parser::McapRecord {
            fn into_into_dart(self) -> crate::api::parser::McapRecord {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::parser::McapSchemaInfo {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.id.into_into_dart().into_dart(),
self.name.into_into_dart().into_dart(),
self.encoding.into_into_dart().into_dart(),
self.data.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::parser::McapSchemaInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::parser::McapSchemaInfo> for crate::api::parser::McapSchemaInfo {
            fn into_into_dart(self) -> crate::api::parser::McapSchemaInfo {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::parser::RecordType {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {
                    Self::Metadata => 0.into_dart(),
Self::Channel => 1.into_dart(),
Self::Schema => 2.into_dart(),
Self::Attachment => 3.into_dart(),
Self::Message => 4.into_dart(),
Self::End => 5.into_dart(),
                    _ => unreachable!(),
                }
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::parser::RecordType {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::parser::RecordType> for crate::api::parser::RecordType {
            fn into_into_dart(self) -> crate::api::parser::RecordType {
                self
            }
        }

                impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(format!("{:?}", self), serializer);}
                }
                
                impl SseEncode for chrono::DateTime::<chrono::Utc> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i64>::sse_encode(self.timestamp_micros(), serializer);}
                }
                
                impl SseEncode for std::collections::HashMap<String, String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<(String,String,)>>::sse_encode(self.into_iter().collect(), serializer);}
                }
                
                impl SseEncode for StreamSink<crate::api::parser::McapRecord,flutter_rust_bridge::for_generated::SseCodec> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {unimplemented!("")}
                }
                
                impl SseEncode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<u8>>::sse_encode(self.into_bytes(), serializer);}
                }
                
                impl SseEncode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_i32::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for i64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_i64::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <u8>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Vec<(String,String,)> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <(String,String,)>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Vec<crate::api::parser::RecordType> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <crate::api::parser::RecordType>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for crate::api::parser::McapAttachmentInfo {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<chrono::DateTime::<chrono::Utc>>::sse_encode(self.log_time, serializer);
<chrono::DateTime::<chrono::Utc>>::sse_encode(self.create_time, serializer);
<String>::sse_encode(self.name, serializer);
<String>::sse_encode(self.media_type, serializer);
<u32>::sse_encode(self.crc, serializer);
<Vec<u8>>::sse_encode(self.data, serializer);}
                }
                
                impl SseEncode for crate::api::parser::McapChannelInfo {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<u16>::sse_encode(self.id, serializer);
<String>::sse_encode(self.topic, serializer);
<String>::sse_encode(self.message_encoding, serializer);
<u16>::sse_encode(self.schema_id, serializer);
<std::collections::HashMap<String, String>>::sse_encode(self.metadata, serializer);}
                }
                
                impl SseEncode for crate::api::parser::McapMessage {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<u16>::sse_encode(self.channel_id, serializer);
<chrono::DateTime::<chrono::Utc>>::sse_encode(self.log_time, serializer);
<chrono::DateTime::<chrono::Utc>>::sse_encode(self.publish_time, serializer);
<Vec<u8>>::sse_encode(self.data, serializer);}
                }
                
                impl SseEncode for crate::api::parser::McapMetadataInfo {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.name, serializer);
<std::collections::HashMap<String, String>>::sse_encode(self.metadata, serializer);}
                }
                
                impl SseEncode for crate::api::parser::McapRecord {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {match self {crate::api::parser::McapRecord::Schema(field0) => { <i32>::sse_encode(0, serializer); <crate::api::parser::McapSchemaInfo>::sse_encode(field0, serializer);
 }
crate::api::parser::McapRecord::Channel(field0) => { <i32>::sse_encode(1, serializer); <crate::api::parser::McapChannelInfo>::sse_encode(field0, serializer);
 }
crate::api::parser::McapRecord::Message(field0) => { <i32>::sse_encode(2, serializer); <crate::api::parser::McapMessage>::sse_encode(field0, serializer);
 }
crate::api::parser::McapRecord::Metadata(field0) => { <i32>::sse_encode(3, serializer); <crate::api::parser::McapMetadataInfo>::sse_encode(field0, serializer);
 }
crate::api::parser::McapRecord::Attachment(field0) => { <i32>::sse_encode(4, serializer); <crate::api::parser::McapAttachmentInfo>::sse_encode(field0, serializer);
 }
crate::api::parser::McapRecord::Error(field0) => { <i32>::sse_encode(5, serializer); <String>::sse_encode(field0, serializer);
 }
crate::api::parser::McapRecord::End => { <i32>::sse_encode(6, serializer);  }
 _ => { unimplemented!(""); }}}
                }
                
                impl SseEncode for crate::api::parser::McapSchemaInfo {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<u16>::sse_encode(self.id, serializer);
<String>::sse_encode(self.name, serializer);
<String>::sse_encode(self.encoding, serializer);
<Vec<u8>>::sse_encode(self.data, serializer);}
                }
                
                impl SseEncode for (String,String,) {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.0, serializer);
<String>::sse_encode(self.1, serializer);}
                }
                
                impl SseEncode for crate::api::parser::RecordType {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(match self {crate::api::parser::RecordType::Metadata => { 0 }
crate::api::parser::RecordType::Channel => { 1 }
crate::api::parser::RecordType::Schema => { 2 }
crate::api::parser::RecordType::Attachment => { 3 }
crate::api::parser::RecordType::Message => { 4 }
crate::api::parser::RecordType::End => { 5 }
 _ => { unimplemented!(""); }}, serializer);}
                }
                
                impl SseEncode for u16 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u16::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u32::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self).unwrap();}
                }
                
                impl SseEncode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
                }
                
                impl SseEncode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self as _).unwrap();}
                }
                


        
        
        #[cfg(not(target_family = "wasm"))]
        mod io {
            // This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_io!();


        }
        #[cfg(not(target_family = "wasm"))]
        pub use io::*;
        
        
        /// cbindgen:ignore
        #[cfg(target_family = "wasm")]
        mod web {
            // This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;
                use flutter_rust_bridge::for_generated::wasm_bindgen;
                use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;


// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_web!();


        }
        #[cfg(target_family = "wasm")]
        pub use web::*;
        