// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/parser.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


                /// Main entrypoint of the Rust API
                class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
                  @internal
                  static final instance = RustLib._();

                  RustLib._();

                  /// Initialize flutter_rust_bridge
                  static Future<void> init({
                    RustLibApi? api,
                    BaseHandler? handler,
                    ExternalLibrary? externalLibrary,
                    bool forceSameCodegenVersion = true,
                  }) async {
                    await instance.initImpl(
                      api: api,
                      handler: handler,
                      externalLibrary: externalLibrary,
                      forceSameCodegenVersion: forceSameCodegenVersion,
                    );
                  }

                  /// Initialize flutter_rust_bridge in mock mode.
                  /// No libraries for FFI are loaded.
                  static void initMock({
                    required RustLibApi api,
                  }) {
                    instance.initMockImpl(
                      api: api,
                    );
                  }

                  /// Dispose flutter_rust_bridge
                  ///
                  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
                  /// is automatically disposed when the app stops.
                  static void dispose() => instance.disposeImpl();

                  @override
                  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

                  @override
                  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

                  @override
                  Future<void> executeRustInitializers() async {
                    await api.crateApiParserInitApp();

                  }

                  @override
                  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

                  @override
                  String get codegenVersion => '2.11.1';

                  @override
                  int get rustContentHash => -1184596833;

                  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
                    stem: 'flutter_mcap_parser',
                    ioDirectory: 'rust/target/release/',
                    webPrefix: 'pkg/',
                  );
                }
                

                abstract class RustLibApi extends BaseApi {
                  Future<void> crateApiParserInitApp();

Stream<McapRecord> crateApiParserParseMcap({required String path , required List<int> buf , required List<RecordType> types });


                }
                

                class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
                  RustLibApiImpl({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  @override Future<void> crateApiParserInitApp()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiParserInitAppConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiParserInitAppConstMeta => const TaskConstMeta(
            debugName: "init_app",
            argNames: [],
        );
        

@override Stream<McapRecord> crateApiParserParseMcap({required String path , required List<int> buf , required List<RecordType> types })  { 
            final sink = RustStreamSink<McapRecord>();
            unawaited(handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(path, serializer);
sse_encode_list_prim_u_8_loose(buf, serializer);
sse_encode_list_record_type(types, serializer);
sse_encode_StreamSink_mcap_record_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiParserParseMcapConstMeta,
            argValues: [path, buf, types, sink],
            apiImpl: this,
        )));
            return sink.stream;
             }


        TaskConstMeta get kCrateApiParserParseMcapConstMeta => const TaskConstMeta(
            debugName: "parse_mcap",
            argNames: ["path", "buf", "types", "sink"],
        );
        



                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return AnyhowException(raw as String); }

@protected DateTime dco_decode_Chrono_Utc(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeTimestamp(ts: dco_decode_i_64(raw).toInt(), isUtc: true); }

@protected Map<String, String> dco_decode_Map_String_String_None(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return Map.fromEntries(dco_decode_list_record_string_string(raw).map((e) => MapEntry(e.$1, e.$2))); }

@protected RustStreamSink<McapRecord> dco_decode_StreamSink_mcap_record_Sse(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
throw UnimplementedError(); }

@protected String dco_decode_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as String; }

@protected McapAttachmentInfo dco_decode_box_autoadd_mcap_attachment_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_mcap_attachment_info(raw); }

@protected McapChannelInfo dco_decode_box_autoadd_mcap_channel_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_mcap_channel_info(raw); }

@protected McapMessage dco_decode_box_autoadd_mcap_message(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_mcap_message(raw); }

@protected McapMetadataInfo dco_decode_box_autoadd_mcap_metadata_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_mcap_metadata_info(raw); }

@protected McapSchemaInfo dco_decode_box_autoadd_mcap_schema_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_mcap_schema_info(raw); }

@protected int dco_decode_i_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected PlatformInt64 dco_decode_i_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeI64(raw); }

@protected List<int> dco_decode_list_prim_u_8_loose(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as List<int>; }

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Uint8List; }

@protected List<(String,String)> dco_decode_list_record_string_string(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_record_string_string).toList(); }

@protected List<RecordType> dco_decode_list_record_type(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_record_type).toList(); }

@protected McapAttachmentInfo dco_decode_mcap_attachment_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
                return McapAttachmentInfo(logTime: dco_decode_Chrono_Utc(arr[0]),
createTime: dco_decode_Chrono_Utc(arr[1]),
name: dco_decode_String(arr[2]),
mediaType: dco_decode_String(arr[3]),
crc: dco_decode_u_32(arr[4]),
data: dco_decode_list_prim_u_8_strict(arr[5]),); }

@protected McapChannelInfo dco_decode_mcap_channel_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
                return McapChannelInfo(id: dco_decode_u_16(arr[0]),
topic: dco_decode_String(arr[1]),
messageEncoding: dco_decode_String(arr[2]),
schemaId: dco_decode_u_16(arr[3]),
metadata: dco_decode_Map_String_String_None(arr[4]),); }

@protected McapMessage dco_decode_mcap_message(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
                return McapMessage(channelId: dco_decode_u_16(arr[0]),
logTime: dco_decode_Chrono_Utc(arr[1]),
publishTime: dco_decode_Chrono_Utc(arr[2]),
data: dco_decode_list_prim_u_8_strict(arr[3]),); }

@protected McapMetadataInfo dco_decode_mcap_metadata_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
                return McapMetadataInfo(name: dco_decode_String(arr[0]),
metadata: dco_decode_Map_String_String_None(arr[1]),); }

@protected McapRecord dco_decode_mcap_record(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
switch (raw[0]) {
                case 0: return McapRecord_Schema(dco_decode_box_autoadd_mcap_schema_info(raw[1]),);
case 1: return McapRecord_Channel(dco_decode_box_autoadd_mcap_channel_info(raw[1]),);
case 2: return McapRecord_Message(dco_decode_box_autoadd_mcap_message(raw[1]),);
case 3: return McapRecord_Metadata(dco_decode_box_autoadd_mcap_metadata_info(raw[1]),);
case 4: return McapRecord_Attachment(dco_decode_box_autoadd_mcap_attachment_info(raw[1]),);
case 5: return McapRecord_Error(dco_decode_String(raw[1]),);
case 6: return McapRecord_End();
                default: throw Exception("unreachable");
            } }

@protected McapSchemaInfo dco_decode_mcap_schema_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
                return McapSchemaInfo(id: dco_decode_u_16(arr[0]),
name: dco_decode_String(arr[1]),
encoding: dco_decode_String(arr[2]),
data: dco_decode_list_prim_u_8_strict(arr[3]),); }

@protected (String,String) dco_decode_record_string_string(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
            if (arr.length != 2) {
                throw Exception('Expected 2 elements, got ${arr.length}');
            }
            return (dco_decode_String(arr[0]),dco_decode_String(arr[1]),); }

@protected RecordType dco_decode_record_type(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return RecordType.values[raw as int]; }

@protected int dco_decode_u_16(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected int dco_decode_u_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected int dco_decode_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected void dco_decode_unit(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return; }

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_String(deserializer);
        return AnyhowException(inner); }

@protected DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_64(deserializer);
        return DateTime.fromMicrosecondsSinceEpoch(inner.toInt(), isUtc: true); }

@protected Map<String, String> sse_decode_Map_String_String_None(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_list_record_string_string(deserializer);
        return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2))); }

@protected RustStreamSink<McapRecord> sse_decode_StreamSink_mcap_record_Sse(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
throw UnimplementedError('Unreachable ()'); }

@protected String sse_decode_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_list_prim_u_8_strict(deserializer);
        return utf8.decoder.convert(inner); }

@protected McapAttachmentInfo sse_decode_box_autoadd_mcap_attachment_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_mcap_attachment_info(deserializer)); }

@protected McapChannelInfo sse_decode_box_autoadd_mcap_channel_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_mcap_channel_info(deserializer)); }

@protected McapMessage sse_decode_box_autoadd_mcap_message(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_mcap_message(deserializer)); }

@protected McapMetadataInfo sse_decode_box_autoadd_mcap_metadata_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_mcap_metadata_info(deserializer)); }

@protected McapSchemaInfo sse_decode_box_autoadd_mcap_schema_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_mcap_schema_info(deserializer)); }

@protected int sse_decode_i_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt32(); }

@protected PlatformInt64 sse_decode_i_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getPlatformInt64(); }

@protected List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected List<(String,String)> sse_decode_list_record_string_string(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <(String,String)>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_record_string_string(deserializer)); }
        return ans_;
         }

@protected List<RecordType> sse_decode_list_record_type(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <RecordType>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_record_type(deserializer)); }
        return ans_;
         }

@protected McapAttachmentInfo sse_decode_mcap_attachment_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_logTime = sse_decode_Chrono_Utc(deserializer);
var var_createTime = sse_decode_Chrono_Utc(deserializer);
var var_name = sse_decode_String(deserializer);
var var_mediaType = sse_decode_String(deserializer);
var var_crc = sse_decode_u_32(deserializer);
var var_data = sse_decode_list_prim_u_8_strict(deserializer);
return McapAttachmentInfo(logTime: var_logTime, createTime: var_createTime, name: var_name, mediaType: var_mediaType, crc: var_crc, data: var_data); }

@protected McapChannelInfo sse_decode_mcap_channel_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_id = sse_decode_u_16(deserializer);
var var_topic = sse_decode_String(deserializer);
var var_messageEncoding = sse_decode_String(deserializer);
var var_schemaId = sse_decode_u_16(deserializer);
var var_metadata = sse_decode_Map_String_String_None(deserializer);
return McapChannelInfo(id: var_id, topic: var_topic, messageEncoding: var_messageEncoding, schemaId: var_schemaId, metadata: var_metadata); }

@protected McapMessage sse_decode_mcap_message(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_channelId = sse_decode_u_16(deserializer);
var var_logTime = sse_decode_Chrono_Utc(deserializer);
var var_publishTime = sse_decode_Chrono_Utc(deserializer);
var var_data = sse_decode_list_prim_u_8_strict(deserializer);
return McapMessage(channelId: var_channelId, logTime: var_logTime, publishTime: var_publishTime, data: var_data); }

@protected McapMetadataInfo sse_decode_mcap_metadata_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_name = sse_decode_String(deserializer);
var var_metadata = sse_decode_Map_String_String_None(deserializer);
return McapMetadataInfo(name: var_name, metadata: var_metadata); }

@protected McapRecord sse_decode_mcap_record(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            var tag_ = sse_decode_i_32(deserializer);
            switch (tag_) { case 0: var var_field0 = sse_decode_box_autoadd_mcap_schema_info(deserializer);
return McapRecord_Schema(var_field0);case 1: var var_field0 = sse_decode_box_autoadd_mcap_channel_info(deserializer);
return McapRecord_Channel(var_field0);case 2: var var_field0 = sse_decode_box_autoadd_mcap_message(deserializer);
return McapRecord_Message(var_field0);case 3: var var_field0 = sse_decode_box_autoadd_mcap_metadata_info(deserializer);
return McapRecord_Metadata(var_field0);case 4: var var_field0 = sse_decode_box_autoadd_mcap_attachment_info(deserializer);
return McapRecord_Attachment(var_field0);case 5: var var_field0 = sse_decode_String(deserializer);
return McapRecord_Error(var_field0);case 6: return McapRecord_End(); default: throw UnimplementedError(''); }
             }

@protected McapSchemaInfo sse_decode_mcap_schema_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_id = sse_decode_u_16(deserializer);
var var_name = sse_decode_String(deserializer);
var var_encoding = sse_decode_String(deserializer);
var var_data = sse_decode_list_prim_u_8_strict(deserializer);
return McapSchemaInfo(id: var_id, name: var_name, encoding: var_encoding, data: var_data); }

@protected (String,String) sse_decode_record_string_string(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_field0 = sse_decode_String(deserializer);
var var_field1 = sse_decode_String(deserializer);
return (var_field0, var_field1); }

@protected RecordType sse_decode_record_type(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return RecordType.values[inner]; }

@protected int sse_decode_u_16(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint16(); }

@protected int sse_decode_u_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint32(); }

@protected int sse_decode_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8(); }

@protected void sse_decode_unit(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected bool sse_decode_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8() != 0; }

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.message, serializer); }

@protected void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_64(PlatformInt64Util.from(self.microsecondsSinceEpoch), serializer); }

@protected void sse_encode_Map_String_String_None(Map<String, String> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_record_string_string(self.entries.map((e) => (e.key, e.value)).toList(), serializer); }

@protected void sse_encode_StreamSink_mcap_record_Sse(RustStreamSink<McapRecord> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.setupAndSerialize(codec: SseCodec(
            decodeSuccessData: sse_decode_mcap_record,
            decodeErrorData: sse_decode_AnyhowException,
        )), serializer); }

@protected void sse_encode_String(String self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer); }

@protected void sse_encode_box_autoadd_mcap_attachment_info(McapAttachmentInfo self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_mcap_attachment_info(self, serializer); }

@protected void sse_encode_box_autoadd_mcap_channel_info(McapChannelInfo self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_mcap_channel_info(self, serializer); }

@protected void sse_encode_box_autoadd_mcap_message(McapMessage self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_mcap_message(self, serializer); }

@protected void sse_encode_box_autoadd_mcap_metadata_info(McapMetadataInfo self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_mcap_metadata_info(self, serializer); }

@protected void sse_encode_box_autoadd_mcap_schema_info(McapSchemaInfo self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_mcap_schema_info(self, serializer); }

@protected void sse_encode_i_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt32(self); }

@protected void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putPlatformInt64(self); }

@protected void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self is Uint8List ? self : Uint8List.fromList(self)); }

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self); }

@protected void sse_encode_list_record_string_string(List<(String,String)> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_record_string_string(item, serializer); } }

@protected void sse_encode_list_record_type(List<RecordType> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_record_type(item, serializer); } }

@protected void sse_encode_mcap_attachment_info(McapAttachmentInfo self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_Chrono_Utc(self.logTime, serializer);
sse_encode_Chrono_Utc(self.createTime, serializer);
sse_encode_String(self.name, serializer);
sse_encode_String(self.mediaType, serializer);
sse_encode_u_32(self.crc, serializer);
sse_encode_list_prim_u_8_strict(self.data, serializer);
 }

@protected void sse_encode_mcap_channel_info(McapChannelInfo self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_u_16(self.id, serializer);
sse_encode_String(self.topic, serializer);
sse_encode_String(self.messageEncoding, serializer);
sse_encode_u_16(self.schemaId, serializer);
sse_encode_Map_String_String_None(self.metadata, serializer);
 }

@protected void sse_encode_mcap_message(McapMessage self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_u_16(self.channelId, serializer);
sse_encode_Chrono_Utc(self.logTime, serializer);
sse_encode_Chrono_Utc(self.publishTime, serializer);
sse_encode_list_prim_u_8_strict(self.data, serializer);
 }

@protected void sse_encode_mcap_metadata_info(McapMetadataInfo self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.name, serializer);
sse_encode_Map_String_String_None(self.metadata, serializer);
 }

@protected void sse_encode_mcap_record(McapRecord self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
switch (self) { case McapRecord_Schema(field0: final field0): sse_encode_i_32(0, serializer); sse_encode_box_autoadd_mcap_schema_info(field0, serializer);
case McapRecord_Channel(field0: final field0): sse_encode_i_32(1, serializer); sse_encode_box_autoadd_mcap_channel_info(field0, serializer);
case McapRecord_Message(field0: final field0): sse_encode_i_32(2, serializer); sse_encode_box_autoadd_mcap_message(field0, serializer);
case McapRecord_Metadata(field0: final field0): sse_encode_i_32(3, serializer); sse_encode_box_autoadd_mcap_metadata_info(field0, serializer);
case McapRecord_Attachment(field0: final field0): sse_encode_i_32(4, serializer); sse_encode_box_autoadd_mcap_attachment_info(field0, serializer);
case McapRecord_Error(field0: final field0): sse_encode_i_32(5, serializer); sse_encode_String(field0, serializer);
case McapRecord_End(): sse_encode_i_32(6, serializer);   } }

@protected void sse_encode_mcap_schema_info(McapSchemaInfo self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_u_16(self.id, serializer);
sse_encode_String(self.name, serializer);
sse_encode_String(self.encoding, serializer);
sse_encode_list_prim_u_8_strict(self.data, serializer);
 }

@protected void sse_encode_record_string_string((String,String) self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.$1, serializer);
sse_encode_String(self.$2, serializer);
 }

@protected void sse_encode_record_type(RecordType self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_u_16(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint16(self); }

@protected void sse_encode_u_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint32(self); }

@protected void sse_encode_u_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self); }

@protected void sse_encode_unit(void self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected void sse_encode_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self ? 1 : 0); }
                }
                
