// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field


// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/parser.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';




                abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
                  RustLibApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  

                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw);

@protected DateTime dco_decode_Chrono_Utc(dynamic raw);

@protected Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

@protected RustStreamSink<McapRecord> dco_decode_StreamSink_mcap_record_Sse(dynamic raw);

@protected String dco_decode_String(dynamic raw);

@protected McapAttachmentInfo dco_decode_box_autoadd_mcap_attachment_info(dynamic raw);

@protected McapChannelInfo dco_decode_box_autoadd_mcap_channel_info(dynamic raw);

@protected McapMessage dco_decode_box_autoadd_mcap_message(dynamic raw);

@protected McapMetadataInfo dco_decode_box_autoadd_mcap_metadata_info(dynamic raw);

@protected McapSchemaInfo dco_decode_box_autoadd_mcap_schema_info(dynamic raw);

@protected int dco_decode_i_32(dynamic raw);

@protected PlatformInt64 dco_decode_i_64(dynamic raw);

@protected List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected List<(String,String)> dco_decode_list_record_string_string(dynamic raw);

@protected List<RecordType> dco_decode_list_record_type(dynamic raw);

@protected McapAttachmentInfo dco_decode_mcap_attachment_info(dynamic raw);

@protected McapChannelInfo dco_decode_mcap_channel_info(dynamic raw);

@protected McapMessage dco_decode_mcap_message(dynamic raw);

@protected McapMetadataInfo dco_decode_mcap_metadata_info(dynamic raw);

@protected McapRecord dco_decode_mcap_record(dynamic raw);

@protected McapSchemaInfo dco_decode_mcap_schema_info(dynamic raw);

@protected (String,String) dco_decode_record_string_string(dynamic raw);

@protected RecordType dco_decode_record_type(dynamic raw);

@protected int dco_decode_u_16(dynamic raw);

@protected int dco_decode_u_32(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

@protected DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

@protected Map<String, String> sse_decode_Map_String_String_None(SseDeserializer deserializer);

@protected RustStreamSink<McapRecord> sse_decode_StreamSink_mcap_record_Sse(SseDeserializer deserializer);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected McapAttachmentInfo sse_decode_box_autoadd_mcap_attachment_info(SseDeserializer deserializer);

@protected McapChannelInfo sse_decode_box_autoadd_mcap_channel_info(SseDeserializer deserializer);

@protected McapMessage sse_decode_box_autoadd_mcap_message(SseDeserializer deserializer);

@protected McapMetadataInfo sse_decode_box_autoadd_mcap_metadata_info(SseDeserializer deserializer);

@protected McapSchemaInfo sse_decode_box_autoadd_mcap_schema_info(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

@protected List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected List<(String,String)> sse_decode_list_record_string_string(SseDeserializer deserializer);

@protected List<RecordType> sse_decode_list_record_type(SseDeserializer deserializer);

@protected McapAttachmentInfo sse_decode_mcap_attachment_info(SseDeserializer deserializer);

@protected McapChannelInfo sse_decode_mcap_channel_info(SseDeserializer deserializer);

@protected McapMessage sse_decode_mcap_message(SseDeserializer deserializer);

@protected McapMetadataInfo sse_decode_mcap_metadata_info(SseDeserializer deserializer);

@protected McapRecord sse_decode_mcap_record(SseDeserializer deserializer);

@protected McapSchemaInfo sse_decode_mcap_schema_info(SseDeserializer deserializer);

@protected (String,String) sse_decode_record_string_string(SseDeserializer deserializer);

@protected RecordType sse_decode_record_type(SseDeserializer deserializer);

@protected int sse_decode_u_16(SseDeserializer deserializer);

@protected int sse_decode_u_32(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

@protected void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

@protected void sse_encode_Map_String_String_None(Map<String, String> self, SseSerializer serializer);

@protected void sse_encode_StreamSink_mcap_record_Sse(RustStreamSink<McapRecord> self, SseSerializer serializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_mcap_attachment_info(McapAttachmentInfo self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_mcap_channel_info(McapChannelInfo self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_mcap_message(McapMessage self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_mcap_metadata_info(McapMetadataInfo self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_mcap_schema_info(McapSchemaInfo self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);

@protected void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_list_record_string_string(List<(String,String)> self, SseSerializer serializer);

@protected void sse_encode_list_record_type(List<RecordType> self, SseSerializer serializer);

@protected void sse_encode_mcap_attachment_info(McapAttachmentInfo self, SseSerializer serializer);

@protected void sse_encode_mcap_channel_info(McapChannelInfo self, SseSerializer serializer);

@protected void sse_encode_mcap_message(McapMessage self, SseSerializer serializer);

@protected void sse_encode_mcap_metadata_info(McapMetadataInfo self, SseSerializer serializer);

@protected void sse_encode_mcap_record(McapRecord self, SseSerializer serializer);

@protected void sse_encode_mcap_schema_info(McapSchemaInfo self, SseSerializer serializer);

@protected void sse_encode_record_string_string((String,String) self, SseSerializer serializer);

@protected void sse_encode_record_type(RecordType self, SseSerializer serializer);

@protected void sse_encode_u_16(int self, SseSerializer serializer);

@protected void sse_encode_u_32(int self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);
                }
                


// Section: wire_class

class RustLibWire implements BaseWire {
            RustLibWire.fromExternalLibrary(ExternalLibrary lib);

            
        }
        @JS('wasm_bindgen') external RustLibWasmModule get wasmModule;

        @JS() @anonymous extension type RustLibWasmModule._(JSObject _) implements JSObject {
            
        }
        