// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'parser.freezed.dart';

            // These functions are ignored because they are not marked as `pub`: `ns_to_datetime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `eq`


            Stream<McapRecord>  parseMcap({required String path , required List<int> buf , required List<RecordType> types }) => RustLib.instance.api.crateApiParserParseMcap(path: path, buf: buf, types: types);

            class McapAttachmentInfo  {
                final DateTime logTime;
final DateTime createTime;
final String name;
final String mediaType;
final int crc;
final Uint8List data;

                const McapAttachmentInfo({required this.logTime ,required this.createTime ,required this.name ,required this.mediaType ,required this.crc ,required this.data ,});

                
                

                
        @override
        int get hashCode => logTime.hashCode^createTime.hashCode^name.hashCode^mediaType.hashCode^crc.hashCode^data.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is McapAttachmentInfo &&
                runtimeType == other.runtimeType
                && logTime == other.logTime&& createTime == other.createTime&& name == other.name&& mediaType == other.mediaType&& crc == other.crc&& data == other.data;
        
            }

class McapChannelInfo  {
                final int id;
final String topic;
final String messageEncoding;
final int schemaId;
final Map<String, String> metadata;

                const McapChannelInfo({required this.id ,required this.topic ,required this.messageEncoding ,required this.schemaId ,required this.metadata ,});

                
                

                
        @override
        int get hashCode => id.hashCode^topic.hashCode^messageEncoding.hashCode^schemaId.hashCode^metadata.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is McapChannelInfo &&
                runtimeType == other.runtimeType
                && id == other.id&& topic == other.topic&& messageEncoding == other.messageEncoding&& schemaId == other.schemaId&& metadata == other.metadata;
        
            }

class McapMessage  {
                final int channelId;
final DateTime logTime;
final DateTime publishTime;
final Uint8List data;

                const McapMessage({required this.channelId ,required this.logTime ,required this.publishTime ,required this.data ,});

                
                

                
        @override
        int get hashCode => channelId.hashCode^logTime.hashCode^publishTime.hashCode^data.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is McapMessage &&
                runtimeType == other.runtimeType
                && channelId == other.channelId&& logTime == other.logTime&& publishTime == other.publishTime&& data == other.data;
        
            }

class McapMetadataInfo  {
                final String name;
final Map<String, String> metadata;

                const McapMetadataInfo({required this.name ,required this.metadata ,});

                
                

                
        @override
        int get hashCode => name.hashCode^metadata.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is McapMetadataInfo &&
                runtimeType == other.runtimeType
                && name == other.name&& metadata == other.metadata;
        
            }

@freezed
                sealed class McapRecord with _$McapRecord  {
                    const McapRecord._();

                     const factory McapRecord.schema(  McapSchemaInfo field0,) = McapRecord_Schema;
 const factory McapRecord.channel(  McapChannelInfo field0,) = McapRecord_Channel;
 const factory McapRecord.message(  McapMessage field0,) = McapRecord_Message;
 const factory McapRecord.metadata(  McapMetadataInfo field0,) = McapRecord_Metadata;
 const factory McapRecord.attachment(  McapAttachmentInfo field0,) = McapRecord_Attachment;
 const factory McapRecord.error(  String field0,) = McapRecord_Error;
 const factory McapRecord.end() = McapRecord_End;

                    

                    
                }

class McapSchemaInfo  {
                final int id;
final String name;
final String encoding;
final Uint8List data;

                const McapSchemaInfo({required this.id ,required this.name ,required this.encoding ,required this.data ,});

                
                

                
        @override
        int get hashCode => id.hashCode^name.hashCode^encoding.hashCode^data.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is McapSchemaInfo &&
                runtimeType == other.runtimeType
                && id == other.id&& name == other.name&& encoding == other.encoding&& data == other.data;
        
            }

enum RecordType {
                    metadata,
channel,
schema,
attachment,
message,
end,
                    ;
                    
                }
            